database:
  image: mysql
  container_name: database.dev
  command: mysqld --user=root --verbose
  volumes:
    - ./dbcreation.sql:/tmp/dbdump.sql
    - ./import.sh:/tmp/import.sh
  ports:
    - "5000:3306"
  environment:
    MYSQL_DATABASE: "octopus"
    MYSQL_USER: "root"
    MYSQL_PASSWORD: "rootroot"
    MYSQL_ROOT_PASSWORD: "rootroot"
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

web:
  build: ./
  ports:
   - "8000:8888"
  volumes:
   - .