version: '3'
services:
  webapp:
    build: ./
    ports:
     - "8000:8888"
    volumes:
     - ./:/usr/src/app

  database:
    image: mysql
    container_name: database.dev
    command: mysqld --user=root --verbose
    ports:
      - "5000:3306"
    environment:
      MYSQL_DATABASE: octopus
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootroot
    volumes:
      - ./dbdump.sql:/docker-entrypoint-initdb.d/dbdump.sql:ro